### PR TITLE
Adding a docker image for Taxi drive tutorial

### PR DESCRIPTION
**Pull request by Bumbleblo**
That contribution is related to issue #51. Currently the image is based in [official tfx image](https://hub.docker.com/r/tensorflow/tfx) with airflow and jupyter notebook dependencies. The installation for airflow is based in that [script](https://github.com/tensorflow/tfx/blob/master/tfx/examples/workshop/setup/setup_demo.sh).

### CODE REVIEW

**Comment by Bumbleblo** [comment]
> This is great start, but there are some things that need to be fixed. I don't think they're major.
> 
> 1. This is using Python 2.7, but TFX now supports Python 3.5+ and we want to focus examples on Python 3 since Python 2 will soon reach EOL.
> 2. I'm getting some errors on `docker-compose up`, see attached.
> 
> [log.txt](https://github.com/tensorflow/tfx/files/3419483/log.txt)

I agree that python 3.5+ is more appropriate for the project, as the last pre-build image don't have python 3.5 I posted the [official image in my personal registry](https://hub.docker.com/r/bumbleblo/official_build_tfx) using the [build script](https://github.com/tensorflow/tfx/blob/master/tfx/tools/docker/build_docker_image.sh) in the master branch. So, I will rewrite the code to be based in that (while we don't have that version in official tfx registry). 

Regarding the problem in docker-compose I have a guess about it however I will analyze that problem more carefully.

**Comment by Bumbleblo** [comment]
I already posted a new version of the [image](https://hub.docker.com/r/bumbleblo/tfx) using python 3.5 based in the image on master branch. About the problem notified in log file I changed the setup.sh file mode, I believe that will solve the problem.

**Comment by rcrowe-google** [comment]
Hi Filipe,

Thanks for your work on this docker image!  It inspired me to create a similar image that goes in a little different direction, with the goal of only creating a clean environment with an appropriate system configuration for running the developer tutorial and other examples.  So I'll be closing this PR and submitting the new code.  Please think of it as a v1.1 of the work you did, and thanks again!

Robert

**Comment by Bumbleblo** [comment]
Hello @rcrowe-google thanks a lot for the feedback. This version you will be creating would solve the issue environment in #51. If you somehow could reference that code (PR or issue), I would be very happy to learn from him. Also, if you can show the next step in 51 (even close it) I would be grateful.

**Comment by rcrowe-google** [comment]
Hi @Bumbleblo - The code is currently being reviewed, so when it gets pushed I'll reference it here.

**Comment by rcrowe-google** [comment]
TFX workshops are currently being significantly updated, which makes this obsolete.

**Pull request closed without merging**
