### PR TITLE
Add AWS SDK boto3 in Dockerfile

### PR DESCRIPTION
**Pull request by Jeffwan**
This PR helps users to leverage existing prebuilt TFX images to use S3. 

Errors with existing images: 
```
INFO:absl:Running driver for CsvExampleGen
INFO:absl:MetadataStore with gRPC connection initialized
INFO:absl:select span = None
INFO:absl:Adding KFP pod name parameterized-tfx-oss-jssk7-1105165278 to execution
INFO:absl:Adding KFP pod name parameterized-tfx-oss-jssk7-1105165278 to execution
INFO:absl:Running executor for CsvExampleGen
INFO:absl:Generating examples.
INFO:absl:Using 1 process(es) for Beam pipeline execution.
INFO:absl:Processing input csv data s3://xx-kubeflow-pipeline-data/taxi/pipeline/chicago_taxi_pipeline/data/* to TFExample.
Traceback (most recent call last):
    File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 360, in <module>
       main()
    .....
 
    File "/opt/venv/lib/python3.6/site-packages/apache_beam/io/filesystems.py", line 204, in match
       return filesystem.match(patterns, limits)
    File "/opt/venv/lib/python3.6/site-packages/apache_beam/io/filesystem.py", line 765, in match
       raise BeamIOError("Match operation failed", exceptions)
                apache_beam.io.filesystem.BeamIOError: Match operation failed with exceptions {'s3://xx-kubeflow-pipeline-data/taxi/pipeline/chicago_taxi_pipeline/data/*': BeamIOError("List operation failed with exceptions {'s3://xx-kubeflow-pipeline-data/taxi/pipeline/chicago_taxi_pipeline/data/': AssertionError('Missing boto3 requirement',)}",)}
```

S3 file system for Python SDK has been implemented in [BEAM-2572](https://issues.apache.org/jira/browse/BEAM-2572). It has been released in [Apache Beam 2.19.0](https://beam.apache.org/blog/beam-2.19.0/).  TFX master supports >2.19.0 beam. We can bring boto3 dependency to address `Missing boto3 requirement` problem. 

boto3 size is not big. Here's the image differences between w/ and w/o boto3. 

```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
seedjeffwan/tfx     0.22.0              6268c0aa2bfe        10 seconds ago      5.75GB
tensorflow/tfx      0.22.0              e032e569bc69        8 weeks ago         5.69GB
```

### CODE REVIEW

**Comment by zhitaoli** [comment]
Given that boto3 is an implementation detail from apache-beam, I think the dependency is better realized from that side instead. Have you reached out to them?

From our side, we are already paying a lot of cost to manage our complex dependencies (and how they fit into other managed environments like Google colab). I think a separate distribution to make TFX working well with AWS will help both org to manage their dependencies better.

**Comment by Jeffwan** [comment]
@zhitaoli 

I have not reach out to apache-beam team yet. If we can make boto3 as part of extras in `apache-beam` package. Do you think we can change to `pip install apache-beam[aws, gcp]` in TFX dockerfile. We literally just need one package to make it work on AWS and I totally understand dependency management is kind of painful in top level projects. Just want to get some insights from you if that's acceptable if we move it to beam layer.

**Comment by zhitaoli** [comment]
@Jeffwan Thanks for the explanation. As you can probably see, `boto3` never really appeared in TFX code base, even if we write an example to run TFX on AWS (because we'd call that from beam side), so adding it from our side would be hard to maintain.

`apache-beam[aws,gcp]` would be easier to admit to our stack. I might need to look at what additional packages (transitively) this brings in recursively before making a firm commitments.

**Comment by Jeffwan** [comment]
@zhitaoli 

Great. Makes sense. Let me sync with beam and come back to this issue.

**Pull request closed without merging**
