### PR TITLE
Fix in rest_simple tutorial notebook

### PR DESCRIPTION
**Pull request by hemanth171**
In the rest_simple.ipynb notebook (https://www.tensorflow.org/tfx/tutorials/serving/rest_simple) there is a piece of code which show the comparison between the prediction and the actual one. But the comparison is done to same prediction vs prediction. But actually it should be between prediction vs test_image.

This is the wrong code which is show in the tutorial:
show(0, 'The model thought this was a {} (class {}), and it was actually a {} (class {})'.format(
  **class_names[np.argmax(predictions[0])]**, test_labels[0], **class_names[np.argmax(predictions[0])]**, test_labels[0]))

But the code should be like below:
show(0, 'The model thought this was a {} (class {}), and it was actually a {} (class {})'.format(
  **class_names[np.argmax(predictions[0])]**, test_labels[0], **class_names[test_images[0]]**, test_labels[0]))

### CODE REVIEW

**Comment by hemanth171** [comment]
@googlebot I signed it!

**Comment by hemanth171** [comment]
@googlebot I signed it!

**Comment by hemanth171** [comment]
@googlebot I fixed it.

**Comment by hemanth171** [comment]
@googlebot I fixed it.

**Comment by hemanth171** [comment]
@google-admin Though i have signed CLA and fixed everything from my side, i could still see nothing has changed. Could you please let me know what should i do from my side to fix this.

**Comment by zhitaoli** [comment]
Hi @hemanth171 I believe this is because the email address you used to send this patch (hemk@paypal.com) is different than your github profile email. I think you need to either change the email used in the git patch, or add this email as (secondary) email address to your github account.

Please let us know if you have further issues after that.

Sorry for the confusion.

**Comment by hemanth171** [comment]
@zhitaoli Ya i saw that i have committed with a different email id. So i closed this pull request, fixed that problem and raised a new pull request (https://github.com/tensorflow/tfx/pull/1012) which have passed all the checks. Could you please review it.

**Pull request closed without merging**
