### PR TITLE
Build docs with `mkdocs`

### PR DESCRIPTION
**Pull request by smokestacklightnin**
This PR builds docs using mkdocs

Remaining tasks
- [X] Add pages not in markdown format
- [X] Fix broken links. Links are broken mostly because they are not currently in `mkdocs` format, or because they point to resources or pages not in the repository
- [X] Add images -- Many images were actually already present
- [X] Add theming using CSS (Thanks @peytondmurray)
- [X] The `proto` submodule is not showing up in the docs because `mkdocstrings` reads docstrings without executing code, but docstrings are only added at run time. We currently show the members of the module and will include their documentation in a subsequent PR

### CODE REVIEW

**Comment by smokestacklightnin** [comment]
@lego0901 All tests are currently passing and the PR is officially ready for review and merge

**Comment by smokestacklightnin** [comment]
@lego0901 All checks pass and the PR is ready for review and merge

**Review by lego0901 — APPROVED** [review]
Thanks!

**Comment by peytondmurray** [comment]
Had to skip a flaky test to get this to pass; merging now, though.

**Pull request merged**
