### PR TITLE
Feature/add gan example

### PR DESCRIPTION
**Pull request by wardVD**

### CODE REVIEW

**Comment by wardVD** [comment]
Is it possible to get an update on this, @tfx-copybara (hope I'm tagging the right account)

**Comment by zhitaoli** [comment]
@rcrowe-google to advise

**Comment by rcrowe-google** [comment]
Thanks Ward, and sorry for the delay in responding to your PR!  I do have one request.  Could you please add a README which discusses your project?
- What your example demonstrates
- How and why you implemented it the way you did
- Advantages and limitations to your approach
- Potential future improvements or modifications
- Metrics and test results

**Comment by wardVD** [comment]
@rcrowe-google Updated. Thank you for the reply.

**Comment by rcrowe-google** [comment]
Sorry for the delay @wardVD !  We'd like to ask you to move this PR to the [TFX-Addons community](https://github.com/tensorflow/tfx-addons) where we are collecting community-contributed examples, components, and libraries.  Thanks!

**Pull request closed without merging**
