### PR TITLE
Moved component imports in taxi pipeline example to top level [master]

### PR DESCRIPTION
**Pull request by foohasmallya**

### CODE REVIEW

**Comment by numerology** [comment]
Hi @foohasmallya is this PR still WIP? Can you briefly describe its purpose? Thanks!

**Comment by foohasmallya** [comment]
Hey @numerology . Thanks for the nudge. This PR and #833 is merge-ready. Component imports were moved to top level (i.e From "from tfx.components.example_gen.csv_example_gen.component import CsvExampleGen" to "from tfx.components import CsvExampleGen") in TFX 0.15. #659 applies the new import format to all examples except taxi_pipeline.py. I made #832 and #833 to the taxi_pipeline.py file to reflect the new import format in the master branch and 0.15 branch respectively.

**Comment by numerology** [comment]
I think this is a script used in the workshop. Added @rcrowe-google for review.

**Comment by foohasmallya** [comment]
Hey @numerology, you're right. The script is from the taxi trips tutorial. It has been changed to include the new component import format. That's pretty much it.

**Comment by foohasmallya** [comment]
Closing this because changes have been made in PR #880

**Comment by foohasmallya** [comment]
@rcrowe-google I noticed that #880 has changes just for the master branch and not the RC. Since the RC isn't official yet, shouldn't the changes be committed to the RC too? Asking because I'm currently spending time on the docs and would like to understand if changes should be proposed to just the master branch or RC too. (By RC, I mean the 0.15 branch that's out) Thanks!

**Pull request closed without merging**
