### PR TITLE
filter proposal initial commit

### PR DESCRIPTION
**Pull request by vulkomilev**
This is my pull request for this proposal https://github.com/tensorflow/tfx-addons/blob/main/proposals/20210525-examplefilter.md

### CODE REVIEW

**Comment by gbaned** [comment]
@vulkomilev Can you please resolve conflicts? Thank you!

**Comment by rthadur** [comment]
@vulkomilev can you please resolve conflicts , thank you

**Comment by casassg** [comment]
hey @vulkomilev I believe you may need to get this PR to https://github.com/tensorflow/tfx-addons repository not TFX. 😄

**Comment by gbaned** [comment]
@vulkomilev Can you please resolve conflicts , Thank you!

**Comment by casassg** [comment]
@gbaned this can be closed, the real PR is on tfx-addons

**Pull request closed without merging**
