### PR TITLE
dial down log level on udf_utils.get_fn

### PR DESCRIPTION
**Pull request by vpipkt**
Error is overkill for this, it pollutes our logs with false negatives.

### CODE REVIEW

**Review by chongkong — APPROVED** [review]
LGTM

**Comment by vpipkt** [comment]
ty @chongkong still need some approval to run github actions workflows

**Comment by chongkong** [comment]
Oh sorry for the delay. there is an internal process for merging the change, and github action is just for external contributor convenience. I've just checked the progress and nudged the internal reviewer. Will keep status posted.

**Comment by vpipkt** [comment]
@chongkong thanks! not sure what the issue is with the CLA check.... let me know if there is anything I need to do

**Pull request merged**
