### PR TITLE
Moved component imports to top level in all the examples

### PR DESCRIPTION
**Pull request by foohasmallya**

### CODE REVIEW

**Comment by 1025KB** [comment]
Oh, Thanks, we will do this after next release to make sure head examples works with latest release

**Comment by foohasmallya** [comment]
Closing this for now @1025KB

**Comment by foohasmallya** [comment]
@1025KB is there anyone who is assigned for this task? If not, please let me know. Happy to help and open to feedback too.

**Comment by foohasmallya** [comment]
@1025KB Kind of new to contributing to other people's open source software so bear with me if I'm a little slow. Yet to go through RELEASE.md and frankly a little lost. Would like to contribute more, to let me know how I can. Thanks!

**Comment by foohasmallya** [comment]
Keeping this open and merging in the next release

**Comment by foohasmallya** [comment]
Closed because imports have been moved to top level

**Comment by 1025KB** [comment]
Thanks!

**Pull request closed without merging**
