### PR TITLE
Update chicago_taxi to keep up with TFX 0.13 release.

### PR DESCRIPTION
**Pull request by tfx-copybara**
Update chicago_taxi to keep up with TFX 0.13 release.

### CODE REVIEW

**Comment by gogasca** [comment]
After the changes, looks like you need to update some of the imports as well in the trainer folder.
in task.py and model.py:

task.py
```
try:
    from tfx.examples.chicago_taxi.trainer import taxi  # pylint: disable=g-import-not-at-top
except ImportError:
    from trainer import taxi  # pylint: disable=g-import-not-at-top

try:
    from tfx.examples.chicago_taxi.trainer import model  # pylint: disable=g-import-not-at-top
except ImportError:
    from trainer import model  # pylint: disable=g-import-not-at-top
```

model.py

```
try:
    from tfx.examples.chicago_taxi.trainer import taxi  # pylint: disable=g-import-not-at-top
except ImportError:
    from trainer import taxi  # pylint: disable=g-import-not-at-top
```

**Comment by mwalenia** [comment]
Since today it's also necessary to limit scikit-learn version to at most 0.20 - version 0.21.0 now requires Python >= 3.5

**Comment by zhitaoli** [comment]
> Since today it's also necessary to limit scikit-learn version to at most 0.20 - version 0.21.0 now requires Python >= 3.5

Thanks for letting us know. I think 'scikit-learn' dependency was pulled from tensorflow-dava-validation. Although 0.21.0 only supports python >= 3.5, I _think_ python 2 users will just ended up using 0.20 without breaking their work?

@paulgc, can you comment on this?

**Comment by mwalenia** [comment]
@zhitaoli @gogasca @ruoyu90 Hi, when can I expect this PR to be merged?

**Comment by ruoyu90** [comment]
This PR will be merged once we finalize 0.13 release. We still had some minor issues related to tutorial but should be able to conclude the release in May.

**Pull request merged**
