### PR TITLE
Presto working version

### PR DESCRIPTION
**Pull request by junhee-yoo**
1. ExampleGen component for Presto
2. user need to pass 'connection_info' to connect Presto.

Signed-off-by: Jun Hee Yoo <junhee.yoo@navercorp.com>

### CODE REVIEW

**Comment by junhee-yoo** [comment]
I signed it!

**Comment by allisontam** [comment]
Hi, I'm an intern at Google who is working on this along with @zhitaoli. We can discuss the minor differences between the PR and our implementation and figure out how to merge the two.

**Comment by junhee-yoo** [comment]
@allisontam 
I'd love to! Thanks for your comment!
What can I do for you?

**Comment by allisontam** [comment]
The main difference is how the Presto connection parameters are passed in. On a whole, we'd like to move towards using protobufs to encode user-supplied configuration. The additional structure makes it easier to check parameters and create custom components.

For now, it is also likely that a Presto example gen will be released as an example custom component rather than an officially supported component.

@junhee-yoo Would that work for you? These changes wouldn't require further work on your part. We hope to release a Presto component in the near future. Thanks!

**Comment by junhee-yoo** [comment]
1. The main difference is how the Presto connection parameters are passed in.
- Thanks for sharing. I also consider about passing connection information with Protobuf but I picked dictionary because I just thought it is simplest way. According your comment, if TFX maintainers decided to use Protobuf for passing user custom things, I have no reason to against it :)
So if you already implemented protobuf based configuration serialization, It is welcome to apply.

2. For now, it is also likely that a Presto example gen will be released as an example custom component rather than an officially supported component.
- I agree with you. I just put this PrestoExampleGen into example_gen module because I have no idea that where should I put this. So if you mind to move this code into somewhere for custom components, it will be appreciated.
And I also wish this Presto support code to be merged and released soon. I'll do my best to make it so. :)

If you mind, would you share your protobuf code before making additional commit? I think using protobuf to pass user custom arguments will be affected to several custom components - I also have some ideas that I'll implement after this PR. So, it will be thankful that you push your change and giving me a chance to prepare the next contribution.

Thanks for your comments. And I'm ready to hear you. :-^)

**Comment by junhee-yoo** [comment]
@allisontam
Hi!
I've read 3c9cc352900c39b2077850555554fc676997236f and now I'm trying to apply 'custom_config' into my presto example_gen component. And I'm sorry that I thought you also working on presto example_gen and you will push your commits on this PR or something. I misunderstood.

**Comment by allisontam** [comment]
@junhee-yoo We are working on presto example_gen and likely will have it out by the end of the week!

The commit you noted above adds support for a field that the presto config will be passed through.

**Comment by junhee-yoo** [comment]
@allisontam 
We are working on presto example_gen and likely will have it out by the end of the week!
-> Thanks for sharing :). Does it mean this PR will be merged after your work?

**Comment by 1025KB** [comment]
Yep we will merge it but with some changes, thanks!

**Pull request merged**
