### PR TITLE
Replace ExecutorClassSpec with BeamExecutorSpec

### PR DESCRIPTION
**Pull request by TomPham97**
ExecutorClassSpec is no longer supported.

### CODE REVIEW

**Comment by gbaned** [comment]
Hi @briron Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @briron Can you please review this PR ? Thank you!

**Comment by gbaned** [comment]
Hi @briron Can you please review this PR ? Thank you!

**Comment by briron** [comment]
Like this [PR](https://github.com/tensorflow/tfx/pull/6421), I'm waiting for the reply from the author.

**Pull request closed without merging**
