### PR TITLE
Prototype remote @component executor

### PR DESCRIPTION
**Pull request by casassg**
Still under work, but the idea here is to have a way to define @component components without having to send the modules to KFP/Vertex and instead serializing from the client on pipeline compilation time.

Need to:
- [x] Serialize executor
- [x] Serialize component
- [ ] Make it optional to use this version

### CODE REVIEW

**Comment by casassg** [comment]
@charlesccychen @zhitaoli wondering if we could apply something like this (I believe this may still not work as it still requires the component to be accessible on the python path, but need to validate it)

Also this is a backwards incompatible change as imports need to be specified inside the function or else it wont really work due to the isolated nature of exec

**Comment by charlesccychen** [comment]
Hey @casassg, is the intention to create something similar to the "KFP light-weight Python component" functionality, where the component is run inside a specified container directly from the entrypoint? Is this to avoid container building, and will the container contain the TFX SDK?

**Comment by casassg** [comment]
Yes, the idea is to replicate KFP lightweight component. The idea is also to make it generic enough so it doesnt require container to run and can be used from LocalDagRunner, KubeflowDagRunner (and v2) and more 

In the case of KFP indeed it would be run as a container since all components are run individually.

Main issue I see w custom components currently is that they require a custom docker image to be built in order to send the component module to the KFP runtime. Instead by serializing most of it and just executing, it allows us to define custom components and send to KFP without docker image (similar to the lightweight component indeed).

Main difference w KFP lightweight is that this can be used in the current python context (while at least last time I checked the KFP component required to be launched into KFP)

**Comment by casassg** [comment]
btw, so far unit tests work. Only change I needed to add is drop support for bytes (are harder to serialize) and move imports inside the function definition (hard one but I cant find a way to avoid this)

**Comment by casassg** [comment]
So, I think this works as of now. I believe NodeWrapper should do the trick at least on KFP as it doesnt need the spec and it doesnt try to import the component class either. 

I need some ideas on how to run integration test for this though

**Comment by charlesccychen** [comment]
One question here -- are we assuming the container used for execution has (the same version of) TFX installed? This use case is slightly different from the KFP one where nothing is assumed to be installed except an appropriate Python environment.

**Comment by casassg** [comment]
Yes. That's the assumption. It's a bit more relaxed than: Assume the image has the module where the custom component was defined. 

Given the other components also share this assumption partially (aka the other components assume the image has X component installed) this seems hard to avoid even with other components.

**Comment by casassg** [comment]
Will reopen and add more commits soon. catching up after PTO

**Pull request closed without merging**
