### PR TITLE
docs: fix wording and remove unnecessary comma

### PR DESCRIPTION
**Pull request by davidxia**

### CODE REVIEW

**Comment by davidxia** [comment]
Hi, @jiyongjung0 if you can review or cc others here who can. Thanks.

**Review by jiyongjung0 — APPROVED** [review]
Thanks!

**Comment by davidxia** [comment]
Thanks feel free to merge as I can’t.

**Review by jiyongjung0 — APPROVED** [review]

**Comment by davidxia** [comment]
Weird not sure why the cla check says “unable to verify author consent.” Maybe temporary failure?

**Comment by jiyongjung0** [comment]
There was an internal collision while submitting two PRs in a row. Now it was all resolved. Thank you for the contribution!

**Pull request merged**
