### PR TITLE
Add support for arrays in BigQueryExampleGen

### PR DESCRIPTION
**Pull request by domedagen**
Addressing the lack of support for arrays/REPEATED as described in [this issue](https://github.com/tensorflow/tfx/issues/1738).

Last PR ended up in a CLA mess, this is not perfect either but at least looks better.

I guess we have to review it again @1025KB ?

### CODE REVIEW

**Comment by domedagen** [comment]
How do I get rid of my other account in the log though? It does appear in git log, but seems to get attached anyway

**Comment by 1025KB** [comment]
You don't need to do anything, I will merge this [PR](https://github.com/tensorflow/tfx/pull/1760) , and it should automatically close your PR.

(we have some delay for merging PR due to internal issues, will try get that in this week)

**Comment by domedagen** [comment]
@1025KB : If you say so. My other account is a Github Enterprise (GHE) account and according to support, I can't login with it on github.com so I can't sign with that.

**Comment by 1025KB** [comment]
No worries, should be fine, as long as we submit the internal change, the github master will be updated/merged

**Comment by domedagen** [comment]
As the official PR is now merged, I can close this

**Pull request closed without merging**
