### PR TITLE
update tfma_basic notebook with correct web link for SlicingSpec

### PR DESCRIPTION
**Pull request by ymodak**
Fixes GitHub #https://github.com/tensorflow/model-analysis/issues/82

### CODE REVIEW

**Review by rcrowe-google — COMMENTED** [review]
Thanks for trying to fix this broken link!  Unfortunately there seem to be other changes to the text, and the link that you've changed is for the `EvalSavedModel`, not the `SliceSpecs`. Could you update to preserve the text and only change the broken link?

**Comment by ymodak** [comment]
@rcrowe-google Thanks for your review. I have updated the PR with those changes.

**Review by rcrowe-google — APPROVED** [review]
LGTM, and thanks!

**Comment by ymodak** [comment]
Can you please help merge this PR? Thanks!

**Comment by rcrowe-google** [comment]
Unfortunately I'm not authorized to merge this pull request - https://screenshot.googleplex.com/6WFg85qTiXPkJMF.  Could you do this as a CL instead and make me the reviewer?

**Review by zhitaoli — APPROVED** [review]

**Comment by jiyongjung0** [comment]
Thank you so much for your contribution.

Unfortunately, the description in the PR has been erased after this PR is created and the broken link has removed. Let me close this PR.

**Pull request closed without merging**
